routes/web.php
<?php

use App\Subject;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {

    $search = isset($request->busca) ? $request->busca : '' ;

    if(isset($search) && !empty($search)) {
        $collection = Subject::searchHome($search);
        $total = count($collection);
    } else {
        $collection = Subject::getAllSubjects(12);
    }


    return view('home', compact('collection', 'search', 'total'));
})->name('home');

Auth::routes();

// Redirect route register
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('/admin', 'HomeController@index')->name('admin');

// Mostra conteúdo do resumo
Route::get('/materia/{id}/{title?}', function ($id){
    $subject = Subject::find($id);
    if($subject) {
        return view('subject', compact('subject'));
    }
})->name('ver.materias');

// Mostra os resumos com a keyword informada
Route::get('/palavra-chave/{id}/{keyword?}', function ($id){
    $collection = Subject::getAllSubjectsForKeywords(12, $id);
    return view('home', compact('collection'));
})->name('keywords');

Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    // Matérias
    Route::resource('materias', 'SubjectController');
    Route::get('/materias', 'SubjectController@index')->name('materias');
    Route::get('/materia/criar', 'SubjectController@create')->name('criar.materias');
    Route::get('/materia/{id}/editar', 'SubjectController@show')->name('editar.materias');

    // Questões
    Route::resource('questoes', 'QuestionController');
    Route::get('/questoes', 'QuestionController@index')->name('questoes');
    Route::get('/questao/criar', 'QuestionController@create')->name('criar.questoes');
    Route::get('/questao/{id}/editar', 'QuestionController@show')->name('editar.questoes');

    // Simulado
    Route::resource('simulados', 'QuizController');
    Route::get('/simulados', 'QuizController@index')->name('simulados');
    Route::get('/simulado/criar', 'QuizController@create')->name('criar.simulados');
    Route::get('/simulado/{id}/{subject}/{subject_id}', 'QuizController@show')->name('fazer.simulados');

    // Estatísticas
    Route::get('/estatisticas', 'StatisticsController@index')->name('estatisticas');

    // Lottery
    Route::get('/mega', 'LotteryController@index')->name('mega');
});

app/Subject.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Facades\DB;

class Subject extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'id', 'subject', 'description', 'content', 'parent_id', 'children_count'
    ];

    protected $hidden = [
        'created_at', 'updated_at'
    ];

    protected $dates = ['deleted_at'];

    public static function getAllSubjects ($page_size)
    {
        return Subject::select('id', 'subject', 'description')
            ->whereNotNull('content')
            ->paginate($page_size);
    }

    public static function getAllSubjectsForKeywords ($page_size, $keyword_id)
    {
        return Subject::select('id', 'subject', 'description')
            ->whereNotNull('content')
            ->whereHas('keywords', function ($query) use ($keyword_id) {
                $query->where('id', $keyword_id);
            })
            ->paginate($page_size);
    }

    public static function searchHome($term)
    {
        return Subject::select('id', 'subject', 'description')
            ->whereNotNull('content')
            ->where('subject', 'like', "%". strtolower($term) . "%")
            ->orWhere('description', 'like', "%". strtolower($term) . "%")
            ->orWhere('content', 'like', "%". strtolower($term) . "%")
            ->paginate(25);
    }

    public static function getSubjectsParent()
    {
        return Subject::all(['id', 'subject'])->sortBy('subject');
    }

    public static function getSubjectsMain()
    {
        return Subject::select('id', 'subject')
            ->where('parent_id', '=', null)
            ->orderBy('subject')
            ->get();
    }

    public static function setKeywords($idSubject, $keywords)
    {
        $keywords = mb_strtolower($keywords);
        $keywords = explode(',', $keywords);
        $keywords = array_filter(array_map('trim', $keywords));
        $keywordsId = [];

        foreach ($keywords as $key => $val) {

            $rsp = DB::table('keywords')->select('id')->where('name', '=', $val)->first();

            if(empty($rsp->id)) {
                $id = DB::table('keywords')->insertGetId(['name' => $val]);
                array_push($keywordsId, $id);
            } else {
                array_push($keywordsId, $rsp->id);
            }
        }

        $subject = Subject::find($idSubject);
        $subject->keywords()->sync($keywordsId);

    }

    public function keywords()
    {
        return $this->belongsToMany('App\Keyword', 'subject_keyword');
    }

    public static function search($term)
    {
        return DB::table('subjects')
            ->where('subject', 'like', "%". strtolower($term) . "%")
            ->orWhere('description', 'like', "%". strtolower($term) . "%")
            ->orWhere('content', 'like', "%". strtolower($term) . "%")
            ->select('id', 'subject', 'description')
            ->distinct()
            ->paginate(25);
    }
}

app/Http/Controllers/Admin/SubjectController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Subject;
use Validator;

class SubjectController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Matérias', 'url' => ''],
        ]);

        $search = $request->busca;

        if(empty($search)) {
            $collection = Subject::getAllSubjects(5);
            $subjectsParent = Subject::getSubjectsParent();
        } else {
            $collection = Subject::search($search);
        }

        return view('admin.subject.index', compact('collection', 'subjectsParent', 'breadcrumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Matérias', 'url' => route('materias')],
            ['title' => 'Criar Matéria', 'url' => ''],
        ]);
        $subjectsParent = Subject::getSubjectsParent();
        return view('admin.subject.create', compact('subjectsParent', 'breadcrumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $validator = $this->validateData($data);

        if($validator->fails())
            return redirect()->back()->withErrors($validator)->withInput();

        $subject = Subject::create($data);

        Subject::setKeywords($subject->id, $data['keywords']);

        return redirect()->route('editar.materias', ['id' => $subject->id])->with('status', 'Matéria inserida com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Matérias', 'url' => route('materias')],
            ['title' => 'Editar Matéria', 'url' => ''],
        ]);
        $collection = Subject::find($id);
        $subjectsParent = Subject::getSubjectsParent();
        return view('admin.subject.edit', compact('collection', 'subjectsParent', 'breadcrumbs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $validator = $this->validateData($data);

        if($validator->fails())
            return redirect()->back()->withErrors($validator)->withInput();

        Subject::find($id)->update($data);

        Subject::setKeywords($id, $data['keywords']);

        return redirect()->back()->with('status', 'Matéria atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Subject::find($id)->delete();

        return redirect()->back();
    }

    protected function validateData($data)
    {
        $rules = [
            'subject'   => 'required|max:100',
            'description' => 'max:300',
        ];

        $messages = [
            'subject.required'    => 'Informe o nome da matéria.',
            'subject.max'         => 'O nome da matéria deve conter no máximo 100 caracteres.',
            'subject.description' => 'A descrição da matéria deve conter no máximo 300 caracteres.',
        ];

        return Validator::make($data, $rules, $messages);

    }
}

resources/views/admin/subject/create.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Criar Matéria" bg="info">
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <div class="col-md-4">
                        <alert message="{{$val}}"></alert>
                    </div>
                @endforeach
            @endif
            <form-head id="createForm" css="" action="{{ route('materias.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="subject">Matéria</label>
                            <input type="text" class="form-control" id="subject" name="subject" maxlength="100" value="{{ old('subject') }}"/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="parent_id"> Categoria </label>
                            <select class="form-control" id="parent_id" name="parent_id">
                                <option style="display:none;" value="0">Selecionar ...</option>
                                @foreach( $subjectsParent as $key => $v)
                                    <option value="{{ $v->id }}" {{ old('parent_id') == $v->id ? 'selected' : '' }}>{{ $v->subject }}</option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="form-group">
                            <label for="keywords">Palavras Chaves</label>
                            <input type="text" class="form-control" id="keywords" name="keywords" placeholder="Separado por vírgulas" value="{{ old('keywords') }}"/>
                        </div>
                    </div>
                </div>


                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" id="description" name="description" maxlength="300" rows="3">{{ old('description') }}</textarea>
                </div>
                <div class="form-group">
                    <label for="content">Conteúdo</label>
                    <textarea id="content" name="content">
                        {{  old('content') }}
                    </textarea>
                </div>

                <button type="submit" class="btn btn-success col-md-3 float-md-right mx-sm-0 mx-md-2 my-2" value="{{ old('data') }}">
                    Salvar
                </button>
            </form-head>
            <a href="{{ route('materias') }}">
                <button class="btn btn-secondary col-md-3 float-md-right my-2">
                    Cancelar
                </button>
            </a>
        </panel>
    </page>
@endsection

@section('js')
    <script>
        $(function () {
            let editor = CKEDITOR.replace('content', {
                height: 400
            });
        });
    </script>
@stop

resources/views/admin/subject/edit.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Editar Matéria" bg="info">
        @php($action =  route('materias') . '/' . $collection->id )
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <div class="col-md-4">
                        <alert message="{{$val}}"></alert>
                    </div>
                @endforeach
            @elseif(session('status'))
                <div class="row">
                    <div class="col-md-12">
                        <alert message="{{ session('status') }}" type="success" icon="check"></alert>
                    </div>
                </div>
            @endif
            <form-head id="editForm" css="" action="{{ $action }}" method="put" enctype="" token="{{ csrf_token() }}">
                <div class="row">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="subject">Matéria</label>
                            <input type="text" class="form-control" id="subject" name="subject" maxlength="100" value="{{ $collection->subject }}"/>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="parent_id"> Categoria </label>
                            <select class="form-control" id="parent_id" name="parent_id">
                                <option style="display:none;" value="0">Selecionar ...</option>
                                @foreach( $subjectsParent as $key => $v)
                                    <option value="{{ $v->id }}" {{ $collection->id == $v->id ? 'selected' : '' }}>
                                        {{ $v->subject }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-8">
                        <div class="form-group">
                            <label for="keywords">Palavras Chaves</label>
                            @php ($keywords = '')
                            @foreach($collection->keywords as $keyword)
                                @php ($keywords .= $keyword->name . ', ')
                            @endforeach
                            @php ($keywords = substr($keywords, 0, -2))
                            <input type="text" class="form-control" id="keywords" name="keywords" placeholder="Separado por vírgulas" value="{{ $keywords }}"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="description">Descrição</label>
                    <textarea class="form-control" id="description" name="description" maxlength="300" rows="3">{{ $collection->description }}</textarea>
                </div>
                <div class="form-group">
                    <label for="content">Conteúdo</label>
                    <textarea id="content" name="content">
                        {{ $collection->content }}
                    </textarea>
                </div>
                <button type="submit" class="btn btn-success btn-block col-md-3 float-md-right mx-sm-0 mx-md-2 my-2">
                    Atualizar
                </button>
            </form-head>
                <a href="{{ route('materias') }}">
                    <button class="btn btn-secondary col-md-3 float-md-right my-2">
                        Cancelar
                    </button>
                </a>
        </panel>
    </page>
@endsection

@section('js')
    <script>
        $(function () {
            let editor = CKEDITOR.replace('content', {
                height: 400
            });

            setTimeout(function() {
                $(".alert").fadeOut();
            }, 5000)
        });
    </script>
@stop

resources/views/admin/subject/index.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        @if($errors->all())
            @foreach($errors->all() as $key => $val)
                <div class="col-md-4">
                    <alert message="{{$val}}"></alert>
                </div>
            @endforeach
        @endif
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Lista de Matérias" bg="info">
            <table-list
                    v-bind:titles="['#', 'Matéria', 'Descrição']"
                    v-bind:items="{{ json_encode($collection) }}"
                    create="{{ route('criar.materias') }}"
                    edit="{{ route('materias') }}"
                    exclude="{{ route('materias') }}"
                    token="{{ csrf_token() }}"
            ></table-list>
            <div class="float-left my-2 total-paginate">
                Total de Registros: <span>{{ $collection->total() }}</span>
            </div>
            <div class="float-right my-2">
                {{ $collection->links() }}
            </div>
        </panel>
    </page>
@endsection