routes/web.php
<?php

use App\Subject;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {

    $search = isset($request->busca) ? $request->busca : '' ;

    if(isset($search) && !empty($search)) {
        $collection = Subject::searchHome($search);
        $total = count($collection);
    } else {
        $collection = Subject::getAllSubjects(12);
    }


    return view('home', compact('collection', 'search', 'total'));
})->name('home');

Auth::routes();

// Redirect route register
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('/admin', 'HomeController@index')->name('admin');

// Mostra conteúdo do resumo
Route::get('/materia/{id}/{title?}', function ($id){
    $subject = Subject::find($id);
    if($subject) {
        return view('subject', compact('subject'));
    }
})->name('ver.materias');

// Mostra os resumos com a keyword informada
Route::get('/palavra-chave/{id}/{keyword?}', function ($id){
    $collection = Subject::getAllSubjectsForKeywords(12, $id);
    return view('home', compact('collection'));
})->name('keywords');

Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    // Matérias
    Route::resource('materias', 'SubjectController');
    Route::get('/materias', 'SubjectController@index')->name('materias');
    Route::get('/materia/criar', 'SubjectController@create')->name('criar.materias');
    Route::get('/materia/{id}/editar', 'SubjectController@show')->name('editar.materias');

    // Questões
    Route::resource('questoes', 'QuestionController');
    Route::get('/questoes', 'QuestionController@index')->name('questoes');
    Route::get('/questao/criar', 'QuestionController@create')->name('criar.questoes');
    Route::get('/questao/{id}/editar', 'QuestionController@show')->name('editar.questoes');

    // Simulado
    Route::resource('simulados', 'QuizController');
    Route::get('/simulados', 'QuizController@index')->name('simulados');
    Route::get('/simulado/criar', 'QuizController@create')->name('criar.simulados');
    Route::get('/simulado/{id}/{subject}/{subject_id}', 'QuizController@show')->name('fazer.simulados');

    // Estatísticas
    Route::get('/estatisticas', 'StatisticsController@index')->name('estatisticas');

    // Lottery
    Route::get('/mega', 'LotteryController@index')->name('mega');
});

app/Quiz.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Quiz extends Model
{

    protected $fillable = [
        'id', 'name', 'total_questions', 'total_rights', 'total_lefts', 'total_answers'
    ];

    protected $casts = [
        'created_at' => 'datetime:d/m/Y',
        'updated_at' => 'datetime:d/m/Y',
    ];

    public static function generateQuiz($quiz_id, $data=[])
    {
        foreach($data['subject_id'] as $n => $subject){

            $questions = DB::table('questions as QST')
                ->select('QST.id')
                ->join('subjects as SUB', 'QST.subject_id','=', 'SUB.id')
                ->orWhere('QST.subject_id','=', $subject)
                ->orWhere('SUB.parent_id', '=', $subject)
                ->limit($data['qtd'][$n])
                ->inRandomOrder()->get();

            $answers = [];
            foreach ($questions as $key => $question) {
                array_push($answers,[
                    'user_id' => $data['user_id'],
                    'question_id' => $question->id,
                    'quiz_id' => $quiz_id,
                ]);
                DB::table('quizzes')->whereId($quiz_id)->increment('total_questions');
                DB::table('questions')->whereId($question->id)->increment('question_count');
            }

            DB::table('quiz_question')->insert($answers);
        }
    }

    public static function setQuiz($data = [], int $idQuiz)
    {
        foreach ($data['question'] as $idQuestion => $question) {

            $idAlternative = array_keys($question);

            DB::table('quiz_question')
                ->where('quiz_id', '=', $idQuiz)
                ->where('question_id', '=', $idQuestion)
                ->update(['alternative_id' => $idAlternative[0]]);
        }
    }

    public static function getAnswers($id, $idSubject)
    {
        return DB::table('quiz_question as ANS')
            ->join('questions as QST', 'ANS.question_id', '=', 'QST.id')
            ->select('ANS.*')
            ->where('ANS.quiz_id', '=', $id)
            ->where('QST.subject_id', '=', $idSubject)
            ->get();
    }

    public static function getSubjectsQuestion($id)
    {
        $resp = [];

        $array = DB::table('quiz_question as QQ')
            ->join('questions as QS', 'QQ.question_id', '=', 'QS.id')
            ->leftJoin('subjects as SB', 'QS.subject_id', '=', 'SB.id')
            ->leftJoin('subjects as SB2', 'QS.subject_id', '=', 'SB2.parent_id')
            ->select('SB.id', 'SB.parent_id')
            ->where('QQ.quiz_id', '=', $id)
            ->groupBy('QS.subject_id')
            ->get();

        foreach ($array as $item) {
            if(!empty($item->parent_id)) {
                $resp[$item->parent_id] = [];
                if(isset($item->parent_id)) {
                    array_push($resp[$item->parent_id], $item->id);
                }
            }
        }

        return $resp;
    }

    public static function getSubjects($id)
    {
        return DB::table('subject')
            ->select('SB.subject', 'SB.id')
            ->where('QQ.quiz_id', '=', $id)
            ->groupBy('QS.subject_id')
            ->get();
    }

    public function questions()
    {
        return $this->belongsToMany('App\Question', 'quiz_question');
    }

    public static function setRights($quizId)
    {
        $rights =  Quiz::countAlternatives($quizId, 1);
        $errors = Quiz::countAlternatives($quizId, 0);
        $total  = $rights + $errors;

        Quiz::find($quizId)->update(['total_rights' => $rights, 'total_lefts' => $errors, 'total_answers' => $total]);

    }

    private static function countAlternatives($quizId, $opt)
    {
        return DB::table('quiz_question as ANS')
            ->join('quizzes as QUI', 'ANS.quiz_id', '=', 'QUI.id')
            ->leftJoin('alternatives as ALT', 'ANS.alternative_id', '=', 'ALT.id')
            ->where('QUI.id',$quizId)
            ->where('ALT.right', $opt)
            ->count();
    }

    public static function getStatistics($rights = true)
    {
        $totalRight = DB::table('quiz_question as ANSs')
            ->join('questions as QST', 'ANS.question_id', '=', 'QST.id')
            ->join('alternatives as ALT', 'ANS.alternative_id', '=', 'ALT.id')
            ->join('subjects as REL', 'QST.subject_id', '=', 'REL.id')
            ->where('ALT.right', '=',$rights)
            ->where('REL.parent_id', '=', null)
            ->select('REL.subject', DB::raw('count(*) as total'))
            ->groupBy('REL.subject_id')
            ->get();

        return $totalRight;
    }

    public static function search($term)
    {
        return DB::table('quizzes')
            ->where('name', 'like', '%'. strtolower($term) . '%')
            ->paginate(25);
    }

}

app/Http/Controllers/Admin/QuizController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Subject;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Quiz;
use Validator;

class QuizController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Simulados', 'url' => ''],
        ]);

        $search = $request->busca;

        if(empty($search))
            $collection = Quiz::select('*')->paginate(10);
        else
            $collection = Quiz::search($search);

        if(!empty($collection) && empty($search)){
            $date = null;
            $time = new \DateTime();
            foreach ($collection as $key => $quiz) {

                $diff = $time->diff($quiz->updated_at);
                $diff = $diff->i;

                if($diff < 5)
                    $date = true;
                Quiz::setRights($quiz->id);
            }

            if($date)
                $collection = Quiz::select('*')->paginate(10);
        }


        return view('admin.quiz.index', compact('collection', 'subjectsParent', 'breadcrumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Simulados', 'url' => route('simulados')],
            ['title' => 'Criar Simulado', 'url' => ''],
        ]);

        $subjectsParent = Subject::getSubjectsMain();

        return view('admin.quiz.create', compact( 'breadcrumbs', 'subjectsParent'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();
        $validator = Validator::make($data, [
            'name' => 'required',
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        $quiz = Quiz::create($data);

        Quiz::generateQuiz($quiz->id, $data);

        $params = [
            'id'         => $quiz->id,
            'subject'    => 'portugues',
            'subject_id' => 4
        ];

        return redirect()->route('fazer.simulados', $params)->with('status', 'Simulado gerado com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, $subject, $subject_id)
    {
        $breadcrumbs = [
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Simulados', 'url' => route('simulados')],
        ];

        $collection = Quiz::find($id);
        $links = Quiz::getSubjectsQuestion($id, $subject_id);
        $answers = Quiz::getAnswers($id, $subject_id);

        foreach ($links as $link){
            $array = Quiz::getAnswers($id, $link);
            $answers = $answers->merge($array);
        }

        foreach ($collection->questions as $key => $question) {
            if (isset($links[$subject_id]) && $question->subject_id != $subject_id) {
                if(!in_array($question->subject_id, (array)$links[$subject_id])) {
                    unset($collection->questions[$key]);
                }
            }
        }

//        return $collection;

        return view('admin.quiz.quiz', compact('collection', 'answers', 'breadcrumbs', 'links'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $validator = Validator::make($data, [
            'question' => 'required',
        ]);

        if($validator->fails()) {
            return redirect()->back()->withErrors($validator)->withInput();
        }

        Quiz::setQuiz($data, $id);

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
    }
}

resources/views/admin/quiz/create.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Criar Simulado" bg="info">
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <div class="row">
                        <div class="col-md-12">
                            <alert message="{{$val}}"></alert>
                        </div>
                    </div>
                @endforeach
            @endif
            <form-head id="createForm" css="" action="{{ route('simulados.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
                <div class="row">
                    <input hidden name="user_id" value="{{ Auth::user()->id }}">
                    <div class="col-md-12">
                        <div class="form-group">
                            <label for="name">Defina um nome para o simulado</label>
                            <input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}"/>
                        </div>
                    </div>
                    <div class="col-md-2 offset-md-2">
                        Quantidade
                    </div>
                    <div class="col-md-6">
                        Matéria
                    </div>
                    @php($n = 4)
                    @while($n > 0)
                        <div class="col-md-2 offset-md-2">
                            <div class="form-group">
                                <input type="text" class="form-control" name="qtd[{{ $n }}]">
                            </div>
                        </div>
                        <div class="col-md-6">
                            <select class="form-control" id="subject_id" name="subject_id[{{ $n }}]">
                                <option style="display:none;" value="0">Selecionar ...</option>
                                @foreach( $subjectsParent as $key => $v)
                                    <option value="{{ $v->id }}">
                                        {{ $v->subject }}
                                    </option>
                                @endforeach
                            </select>
                            @php($n--)
                        </div><br>
                    @endwhile
                    <div class="col-md-12">
                        <button type="submit" class="btn btn-success col-md-3 float-md-right mx-md-2 my-4" value="{{ old('data') }}">
                            Criar
                        </button>
                        <a href="{{ route('simulados') }}">
                            <button type="button" class="btn btn-secondary col-md-3 float-md-right my-4">
                                Cancelar
                            </button>
                        </a>
                    </div>
                </div>
            </form-head>
        </panel>
    </page>
@endsection

resources/views/admin/quiz/index.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        @if($errors->all())
            @foreach($errors->all() as $key => $val)
                <div class="col-md-12">
                    <alert message="{{$val}}"></alert>
                </div>
            @endforeach
        @endif
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Lista de Questões" bg="info">
            <table-list
                    v-bind:titles="['#', 'Nome', 'Questões', 'Acertos', 'Erros', 'Respostas','Criação', 'Atualiação']"
                    v-bind:items="{{ json_encode($collection) }}"
                    create="{{ route('criar.simulados') }}"
                    quiz="true"
            ></table-list>
            <div class="float-left my-2 pagination total-paginate">
                Total de Registros: <span>{{ $collection->total() }}</span>
            </div>
            <div class="float-right my-2">
                {{ $collection->links() }}
            </div>
        </panel>
    </page>
@endsection

resources/views/admin/quiz/quiz.blade.php
@extends('layouts.app')

<style>
    .box-result {
        position: fixed;
        border: 1px solid;
        padding: 14px 26px 0px;
        top: 40%;
        right: 8.85%;
        box-shadow: 2px 4px 1px #88888842;
        z-index: -1;
    }

    @media (min-width: 1250px) and  (max-width: 1500px) {
        .box-result {
            right: 1%;
        }
    }
    @media (max-width: 1250px) {
        .box-result {
            position: relative;
            border: 1px solid;
            display: inline-flex;
            padding: 15px 26px 0px;
            top: 0;
            right: 0;
            box-shadow: 2px 4px 1px #88888842;
            z-index: 1;
        }

        .box-result p:first-child {
            padding-right: 25px;
        }

        .box-result p:last-child {
            padding-left: 20px;
        }
    }

    .note-alert {
        position: relative;
        -webkit-animation: note-alert 1s infinite alternate; /* Safari 4.0 - 8.0 */
        animation: note-alert 1s infinite alternate;
    }

    /* Safari 4.0 - 8.0 */
    @-webkit-keyframes note-alert {
        from {transform: scale(0.8);}
        to {transform: scale(1.5);}
    }

    @keyframes note-alert {
        from {transform: scale(0.7);}
        to {transform: scale(1.5);}
    }

    hr {
        margin-top: 2rem;
        margin-bottom: 2rem;
        border: 0;
        border-top: 2px dashed rgba(0, 0, 0, 0.27);
    }

    .custom-control.custom-radio {
        border-radius: 6px;
        padding-left: 28px;
    }

</style>

@section('content')
    <page size="12">
        @if($errors->all())
            @foreach($errors->all() as $key => $val)
                <div class="row">
                    <div class="col-md-12">
                        <alert message="{{$val}}"></alert>
                    </div>
                </div>
            @endforeach
        @elseif(session('status'))
            <div class="row">
                <div class="col-md-12">
                    <alert message="{{ session('status') }}" type="success" icon="check"></alert>
                </div>
            </div>
        @endif
        @php(array_push($breadcrumbs, ['title' => ucfirst($collection->name) . ' - ' . ucfirst(Request::route('subject')), 'url' => '']))
        <breadcrumbs v-bind:list="{{json_encode($breadcrumbs)}}"></breadcrumbs>

        @php ($subject_id = Request::route('subject_id') )

            <nav class="nav nav-pills nav-fill my-3">
                <a class="nav-item nav-link {{ $subject_id == 4 ? 'active' : '' }}"
                   href="{{ route('fazer.simulados', [$collection->id, 'portugues', 4]) }}">Português</a>
                <a class="nav-item nav-link {{ $subject_id == 3 ? 'active' : '' }}"
                   href="{{ route('fazer.simulados', [$collection->id, 'historia', 3]) }}">História</a>
                <a class="nav-item nav-link {{ $subject_id == 2 ? 'active' : '' }}"
                   href="{{ route('fazer.simulados', [$collection->id, 'geografia', 2]) }}">Geografia</a>
                <a class="nav-item nav-link {{ $subject_id == 1 ? 'active' : '' }}"
                   href="{{ route('fazer.simulados', [$collection->id, 'informatica', 1]) }}">Informática</a>
            </nav>

        <panel title="{{ $collection->name }}" bg="info">
            @php($action =  route('simulados') . '/' . $collection->id )
            <form-head id="createForm" css="" action="{{ $action }}" method="put" enctype="" token="{{ csrf_token() }}">
                <div class="row">
                    <div class="col-md-12">
                        @php ($countErros = 0)
                        @php ($countRights = 0)
                        @php ($total = 0)
                        @foreach( $collection->questions as $question )
                            @php(isset($links[$subject_id]) ? $links[$subject_id] : $links[$subject_id] = [])
                            @if( $question->subject_id == $subject_id || in_array($question->subject_id, $links[$subject_id]) )
                                @php ($total++)
                                <p class="text-justify"><b>({{ $question->institute }} - {{ $question->year }})</b> {!! $question->question !!} </p>
                                <div class="form-group">
                                    @foreach( $question->alternatives as $alternative )
                                        @php ($right = false)
                                        @php ($answerID = null)
                                        @php ($answered = null)
                                        @foreach( $answers as $key => $answer )
                                            @if( $answer->alternative_id && $question->id == $answer->question_id )
                                                @php ($answered = true)
                                                @if( $question->id == $answer->question_id && $alternative->right !== 0 && $alternative->id == $answer->alternative_id )
                                                    @php($right = true)
                                                    @php ($countRights++)
                                                @endif
                                            @if( $alternative->right !== 1 && $alternative->id == $answer->alternative_id)
                                                    @php($answerID = $answer->alternative_id)
                                                    @php($countErros++)
                                                @endif
                                            @endif
                                        @endforeach
                                            <div class="custom-control custom-radio col-md-12 my-2 {{ ($alternative->right && $answered) ? 'text-success font-weight-bold' : '' }}{{ (!$alternative->right && $answerID) ? 'text-danger font-weight-bold' : '' }}">

                                                <input type="checkbox"
                                                       id="question[{{ $question->id }}][{{ $alternative->id }}]"
                                                       name="question[{{ $question->id }}][{{ $alternative->id }}]"
                                                       class="custom-control-input" {{ (($alternative->right && $answered) && ($alternative->right && $right)) ? 'checked' : '' }}{{ (!$alternative->right && $answerID) ? 'checked' : '' }}>
                                                <label class="custom-control-label" for="question[{{ $question->id }}][{{ $alternative->id }}]">
                                                    {{ $alternative->alternative }}
                                                </label>
                                            </div>
                                    @endforeach
                                </div>
                                <hr>
                            @endif
                        @endforeach

                        @if($countRights != 0 || $countErros != 0)
                            @php( $noteTotalRight =  number_format(($countRights * 100 / ($countRights + $countErros)), 1, '.', ','))
                            <div class="box-result bg-dark text-white">
                                <p data-toggle="tooltip" data-placement="top" title="{{ $noteTotalRight }}"><i class="fas fa-check-circle text-success"></i> {{ $countRights }}</p>
                                <p data-toggle="tooltip" data-placement="top" title="{{ (100 - $noteTotalRight) }}"><i class="fas fa-times-circle text-danger {{ $noteTotalRight <= 70 ? 'note-alert' : ''}}"></i> {{ $countErros }}</p>
                                <p><i class="fas fa-edit text-{{ (($countRights + $countErros) == $total) ? 'secondary' : 'warning' }}"></i>
                                    {{ $countRights + $countErros }} / {{ $total }}
                                </p>
                            </div>
                        @endif

                        <button type="submit" class="btn btn-success col-md-3 float-md-right mx-sm-0 mx-md-2 my-2" value="{{ old('data') }}">
                            Salvar
                        </button>
                        <a href="{{ route('simulados') }}">
                            <button type="button" class="btn btn-secondary col-md-3 float-md-right my-2">
                                Sair
                            </button>
                        </a>
                    </div>
                </div>
            </form-head>
        </panel>
    </page>
@endsection

@section('js')
    <script>
        $(function () {
            setTimeout(function() {
                $(".alert").fadeOut();
            }, 5000)
        });
    </script>
@stop