routes/web.php
<?php

use App\Subject;
use Illuminate\Http\Request;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function (Request $request) {

    $search = isset($request->busca) ? $request->busca : '' ;

    if(isset($search) && !empty($search)) {
        $collection = Subject::searchHome($search);
        $total = count($collection);
    } else {
        $collection = Subject::getAllSubjects(12);
    }


    return view('home', compact('collection', 'search', 'total'));
})->name('home');

Auth::routes();

// Redirect route register
Route::match(['get', 'post'], 'register', function(){
    return redirect('/');
});

Route::get('/admin', 'HomeController@index')->name('admin');

// Mostra conteúdo do resumo
Route::get('/materia/{id}/{title?}', function ($id){
    $subject = Subject::find($id);
    if($subject) {
        return view('subject', compact('subject'));
    }
})->name('ver.materias');

// Mostra os resumos com a keyword informada
Route::get('/palavra-chave/{id}/{keyword?}', function ($id){
    $collection = Subject::getAllSubjectsForKeywords(12, $id);
    return view('home', compact('collection'));
})->name('keywords');

Route::middleware('auth')->prefix('admin')->namespace('Admin')->group(function(){
    // Matérias
    Route::resource('materias', 'SubjectController');
    Route::get('/materias', 'SubjectController@index')->name('materias');
    Route::get('/materia/criar', 'SubjectController@create')->name('criar.materias');
    Route::get('/materia/{id}/editar', 'SubjectController@show')->name('editar.materias');

    // Questões
    Route::resource('questoes', 'QuestionController');
    Route::get('/questoes', 'QuestionController@index')->name('questoes');
    Route::get('/questao/criar', 'QuestionController@create')->name('criar.questoes');
    Route::get('/questao/{id}/editar', 'QuestionController@show')->name('editar.questoes');

    // Simulado
    Route::resource('simulados', 'QuizController');
    Route::get('/simulados', 'QuizController@index')->name('simulados');
    Route::get('/simulado/criar', 'QuizController@create')->name('criar.simulados');
    Route::get('/simulado/{id}/{subject}/{subject_id}', 'QuizController@show')->name('fazer.simulados');

    // Estatísticas
    Route::get('/estatisticas', 'StatisticsController@index')->name('estatisticas');

    // Lottery
    Route::get('/mega', 'LotteryController@index')->name('mega');
});

app/Question.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\DB;

class Question extends Model
{

    protected $fillable = [
        'id', 'question', 'institute', 'year', 'subject_id', 'question_count'
    ];

    public static function getAllQuestions($page_size)
    {
        return DB::table('questions as QST')
                ->join('subjects as SUB', 'QST.subject_id', '=', 'SUB.id')
                ->select('QST.id',
                    'QST.question',
                    'QST.year',
                    'QST.question_count',
                    'SUB.subject')
                ->orderBy('id')
                ->paginate($page_size);
    }

    public static function setAlternatives($questionId, $alternatives=[], $right=[], $update)
    {
        $alternatives = array_filter($alternatives);

        if($update) {
            $alternativesId = [];
            foreach ($alternatives as $key => $alternative) {
                array_push($alternativesId, $key);
            }

            Alternative::destroy($alternativesId);
        }

        foreach ($alternatives as $key => $alternative) {

            if(!empty($right[$key]))
                $isRight = 1;
            else
                $isRight = 0;

            DB::table('alternatives')
                ->insert(['alternative' => $alternative, 'question_id' => $questionId, 'right' => $isRight]);
        }
    }

    public function alternatives()
    {
        return $this->hasMany('App\Alternative');
    }

    public function Quizzes()
    {
        return $this->belongsToMany('App\Quiz');
    }

    public static function search($term)
    {
        return DB::table('questions as QST')
            ->join('alternatives as ALT', 'QST.id', '=', 'ALT.question_id')
            ->join('subjects as SUB', 'QST.subject_id', '=', 'SUB.id')
            ->where('QST.question', 'like', "%". strtolower($term) . "%")
            ->orWhere('ALT.alternative', 'like', "%". strtolower($term) . "%")
            ->orWhere('SUB.subject', 'like', "%". strtolower($term) . "%")
            ->select('QST.id', 'QST.question', 'QST.year', 'QST.question_count', 'SUB.subject')
            ->distinct()
            ->paginate(25);
    }
}

app/Http/Controllers/Admin/QuestionController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Question;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Subject;
use Validator;

class QuestionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Questões', 'url' => ''],
        ]);

        $search = $request->busca;

        if(empty($search))
            $collection = Question::getAllQuestions(10);
        else
            $collection = Question::search($search);

        return view('admin.question.index', compact('collection', 'breadcrumbs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Questões', 'url' => route('questoes')],
            ['title' => 'Criar Questão', 'url' => ''],
        ]);

        $subjectsParent = Subject::getSubjectsParent();

        return view('admin.question.create', compact('subjectsParent', 'breadcrumbs'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $request->all();

        $data['question'] = $data['content'];

        $validator = $this->validateData($data);

        if($validator->fails())
            return redirect()->back()->withErrors($validator)->withInput();

        $question = Question::create($data);

        isset($data['right']) ? $data['right'] : $data['right'] = [];

        Question::setAlternatives($question->id, $data['alternatives'], $data['right'], false);

        return redirect()->route('editar.questoes', ['id' => $question->id])->with('status', 'Questão inserida com sucesso!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $breadcrumbs = json_encode([
            ['title' => 'Dashboard', 'url' => route('admin')],
            ['title' => 'Questões', 'url' => route('questoes')],
            ['title' => 'Editar Questão', 'url' => ''],
        ]);
        $collection = Question::find($id);
        $subjectsParent = Subject::getSubjectsParent();

        return view('admin.question.edit', compact('collection', 'subjectsParent', 'breadcrumbs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $data = $request->all();

        $data['question'] = !empty($data['content']) ? $data['content'] : null;

        $validator = $this->validateData($data);

        if($validator->fails())
            return redirect()->back()->withErrors($validator)->withInput();

        Question::find($id)->update($data);

        isset($data['right']) ? $data['right'] : $data['right'] = [];

        Question::setAlternatives($id, $data['alternatives'], $data['right'], true);

        return redirect()->back()->with('status', 'Questão atualizada com sucesso!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $questions = Question::find($id);
        $questions->alternatives()->delete();
        $questions->delete();

        return redirect()->back();
    }

    protected function validateData($data)
    {
        $rules = [
            'subject_id' => 'required|not_in:0',
            'question' => 'required',
            'year' => 'nullable|min:4|max:4',
            'alternatives' => 'required',
        ];

        $messages = [
            'subject_id.required'  => 'Selecione a matéria',
            'subject_id.not_in'    => 'Selecione a matéria',
            'question.required'    => 'Defina um enunciado para a questão',
            'year.min'             => 'O ano não pode ter menos de 4 caracteres',
            'year.max'             => 'O ano não pode ter mais de 4 caracteres',
            'alternatives.required'=> 'Informe alterantivas para a questão'
        ];

        return Validator::make($data, $rules, $messages);

    }
}

resources/views/admin/question/create.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Criar Matéria" bg="info">
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <div class="row">
                        <div class="col-md-12">
                            <alert message="{{$val}}"></alert>
                        </div>
                    </div>
                @endforeach
            @endif
            <form-head id="createForm" css="" action="{{ route('questoes.store') }}" method="post" enctype="" token="{{ csrf_token() }}">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="subject_id"> Matéria </label>
                            <select class="form-control" id="subject_id" name="subject_id">
                                <option style="display:none;" value="0">Selecionar ...</option>
                                @foreach( $subjectsParent as $key => $v)
                                    <option value="{{ $v->id }}" {{ old('subject_id') == $v->id ? 'selected' : '' }}>
                                        {{ $v->subject }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="institute">Banca/ Instituição</label>
                            <input type="text" class="form-control" id="institute" name="institute" value="{{ old('institute') }}"/>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="year">Banca/ Instituição</label>
                            <input type="number" min="1990" max="{{ date("Y") }}"  class="form-control" id="year" name="year" value="{{ old('year') }}"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="question">Enúnciado da questão</label>
                    <textarea id="content" name="content">
                        {{ old('question') }}
                    </textarea>
                </div>

                <alternatives></alternatives>

                <button type="submit" class="btn btn-success col-md-3 float-md-right mx-sm-0 mx-md-2 my-2" value="{{ old('data') }}">
                    Salvar
                </button>
            </form-head>
            <a href="{{ route('questoes') }}">
                <button class="btn btn-secondary col-md-3 float-md-right my-2">
                    Cancelar
                </button>
            </a>
        </panel>
    </page>
@endsection

@section('js')
    <script>
        $(function () {
            let editor = CKEDITOR.replace('content', {
                height: 400
            });
        });
    </script>
@stop

resources/views/admin/question/edit.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Criar Matéria" bg="info">
            @if($errors->all())
                @foreach($errors->all() as $key => $val)
                    <div class="row">
                        <div class="col-md-12">
                            <alert message="{{$val}}"></alert>
                        </div>
                    </div>
                @endforeach
            @elseif(session('status'))
                <div class="row">
                    <div class="col-md-12">
                        <alert message="{{ session('status') }}" type="success" icon="check"></alert>
                    </div>
                </div>
            @endif
            @php($action =  route('questoes') . '/' . $collection->id )
            <form-head id="createForm" css="" action="{{ $action }}" method="put" enctype="" token="{{ csrf_token() }}">
                <div class="row">
                    <div class="col-md-4">
                        <div class="form-group">
                            <label for="subject_id"> Matéria </label>
                            <select class="form-control" id="subject_id" name="subject_id">
                                <option style="display:none;" value="0">Selecionar ...</option>
                                @foreach( $subjectsParent as $key => $v)
                                    <option value="{{ $v->id }}" {{ $collection->subject_id == $v->id ? 'selected' : '' }}>
                                        {{ $v->subject }}
                                    </option>
                                @endforeach
                            </select>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="form-group">
                            <label for="institute">Banca/ Instituição</label>
                            <input type="text" class="form-control" id="institute" name="institute" value="{{ $collection->institute }}"/>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="year">Ano</label>
                            <input type="number" min="1990" max="{{ date("Y") }}" class="form-control" id="year" name="year" value="{{ $collection->year }}"/>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="question">Enúnciado da questão</label>
                    <textarea id="content" name="content">
                        {{ $collection->question }}
                    </textarea>
                </div>

            <div class="form-group">
                <div class="row">
                    <span class="col-md-6">
                        <label for="alternative">Alternativas <small> (Marque a correta)</small></label>
                    </span>
                </div>
                <span id="editors" class="form-inline form-check-inline">
                @foreach($collection->alternatives as $alternative)
                    <input type="checkbox" id="right_{{$alternative->id}}" name="right[{{ $alternative->id }}]" class="form-control my-2 col-sm-1" {{ $alternative->right != 0 ? 'checked' : '' }}>
                    <input type="text" id="alternative_{{ $alternative->id }}" name="alternatives[{{ $alternative->id }}]" class="form-control my-2 col-sm-11" value="{{ $alternative->alternative }}">
                @endforeach
                </span>
            </div>

                <button type="submit" class="btn btn-success col-md-3 float-md-right mx-sm-0 mx-md-2 my-2" value="{{ old('data') }}">
                    Salvar
                </button>
            </form-head>
            <a href="{{ route('questoes') }}">
                <button class="btn btn-secondary col-md-3 float-md-right my-2">
                    Cancelar
                </button>
            </a>
        </panel>
    </page>
@endsection

@section('js')
    <script>
        $(function () {
            let editor = CKEDITOR.replace('content', {
                height: 400
            });

            setTimeout(function() {
                $(".alert").fadeOut();
            }, 5000)
        });
    </script>
@stop

resources/views/admin/question/index.blade.php
@extends('layouts.app')

@section('content')
    <page size="12">
        @if($errors->all())
            @foreach($errors->all() as $key => $val)
                <div class="col-md-12">
                    <alert message="{{$val}}"></alert>
                </div>
            @endforeach
        @endif
        <breadcrumbs v-bind:list="{{$breadcrumbs}}"></breadcrumbs>
        <panel title="Lista de Questões" bg="info">
            <table-list
                    v-bind:titles="['#', 'Questão', 'Ano', 'Respostas', 'Matéria']"
                    v-bind:items="{{ json_encode($collection) }}"
                    create="{{ route('criar.questoes') }}"
                    edit="{{ route('questoes') }}"
            ></table-list>
            <div class="float-left my-2 pagination total-paginate">
                Total de Registros: <span>{{ count($collection) }}</span>
            </div>
            <div class="float-right my-2">
                {{ $collection->links() }}
            </div>
        </panel>
    </page>
@endsection